# Generated by Django 3.2.9 on 2022-01-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
