# Generated by Django 3.2.9 on 2022-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('default', None), ('quote', 'quote'), ('reply', 'answer')], default=None, max_length=16),
        ),
    ]
