# Generated by Django 3.2.9 on 2022-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[(None, 'default'), ('quote', 'quote'), ('reply', 'answer')], default='default', max_length=16),
        ),
    ]
